### ISSUE TITLE
Multiple address read?

### ISSUE THREAD

**Issue by nevadavid** [patrick--/node-omron-fins#11]
Is it possible to read on multiple address?
For example:
`.read(['D00000', 'D12345', 'D32145']);`

**Comment by patrick--** [comment]
With the current implementation you would need to issue multiple read commands. If the registers are close enough in memory you could just issue a single command that encompasses the entire range required.

**Comment by nevadavid** [comment]
Can I store them in a line of files divide semicolon?
```
client.read('D00000',1);
client.read('D12345',1);
client.read('D32145',1);
```
Line of file: 2018.02.27;321;3213;121

**Comment by patrick--** [comment]
@nevadavid So you want to read three values, then write those to a file?

**Comment by nevadavid** [comment]
@patrick-- exactly

**Comment by ceremcem** [comment]
I *think* this should be handled in the application, not in the library.
