### ISSUE TITLE
License for the project?

### ISSUE THREAD

**Issue by jcjaredevans** [patrick--/node-omron-fins#16]
Noticed you haven't assigned a license for the project yet, from my experience it definitely gets more complicated over time as you have more contributors/copyright holders. Also, some people may not be able to contribute because of employer IP agreements if a license isn't assigned (I'm in this boat). 

If you are going for open-source, Github's licensing site has good advice: https://opensource.guide/legal/, https://choosealicense.com/

Looking forward to contributing to the project!

**Comment by patrick--** [comment]
@jcjaredevans Sorry for the long delay, but in case you are interested I did add a licence.
