### ISSUE TITLE
Reading other than memory area D

### ISSUE THREAD

**Issue by danibjor** [patrick--/node-omron-fins#5]
I tried to read data from memory area HR. 

Googled around a bit and found HR to be 0x80. 
I've updated the constants.js file to include HR area like this:

```
module.exports.MemoryAreas = {
    'H' : 0x80,
    'D' : 0x82
};
```

I've added a `console.log(temp)` to fins_client.js' `_translateMemoryAddress` function just to verify that MemoryArea is in fact set to 0x80.

I do a simple `.read('H00300', 24)` and do a `console.log(msg)` in the 'reply' event method: 

```
{
  remotehost: '10.0.0.233',
  sid: 9,
  command: '0101',
  response: '0000',
  values: [ 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0 ] 
}
```

In Omron Sysmac Studio, we inspect the H3xx memory area and it dones not look like this. Values should be like [big integer, 0, 2, ...]

Any ideas?

**Comment by danibjor** [comment]
I could add that reading from D works fine - so the question really is if the headers or something else should change when reading from DM to HR (other than memoryArea byte)

**Comment by danibjor** [comment]
Fixed it - HR register is +0xB2, not 0x80

**Comment by patrick--** [comment]
Hi Danibjor,

Sorry for the late response. If you have any other problems let me know.
If you haven't seen this already, this manual will have memory codes  and other helpful information:
http://omron.com.ru/dynamic/managers/manage_8/files/w342e1-3.pdf

**Comment by danibjor** [comment]
Added a pull request with update to read HR register.

**Comment by arkypita** [comment]
Hi all, does anyone know if it is possible to read EM Area of omron PLC via fins command?
I can't find a reference to what command code should be use.

![image](https://user-images.githubusercontent.com/8782035/44846650-3a956d80-ac51-11e8-9834-1e05302103ed.png)

**Comment by side105** [comment]
yes, you have to use 0xA0 command. (see complete list below)

            /// <summary>Extended Memories</summary>
            EM = 0xA0,
            /// <summary>CIO</summary>
            CIO = 0xB0,
            /// <summary>Work Area</summary>
            WR = 0xB1,
            /// <summary>Holding Bit</summary>
            HR = 0xB2,
            /// <summary>Auxiliary Bit</summary>
            A = 0xB3,
            /// <summary>Data Memories</summary>
            DM = 0x82

**Comment by arkypita** [comment]
Thanks a lot, you save my day
